### ISSUE TITLE
请问有爬完之后的数据吗？

### ISSUE THREAD

**Issue by taseikyo** [blogstorm/cnblog-spider#1]
最近谷歌到几篇博客园的博客，感觉质量不错，然后来 GitHub 搜博客园的爬虫，发现还是有很多相关项目，但有些挺早了（16 年），看到这个还挺新的，就想问一下有爬完的数据吗？如果有的话能否发我一份？万分感谢 :3

**Comment by zu1k** [comment]
好像没有数据，这个项目是一个作业的附属项目，当初考评完了后啥都删了
